groups:
  - name: TrilhaInstanceAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="trilha/services"} < 1
        for: 20m
        labels:
          severity: error
        annotations:
          description: "A instância {{ $labels.instance }} do job {{ $labels.job }} está há vinte minutos fora do ar."
          summary: "Instancia {{ $labels.instance }} fora do ar"
